/* Service worker.
 *
 * STRATEGY — network-first for code, cache-first for media. This is not a
 * preference. Two apps in this fleet independently shipped cache-first and had
 * to rip it out because it kept serving the previous engine.js/view.js after a
 * deploy (see dice/underfoot/sw.js and bubbles/sw.js). Do not invert it back.
 *
 * The `cache: 'no-store'` on the network leg is the part both of those still
 * miss: fetch() inside a service worker goes through the browser's ordinary
 * HTTP cache, so without it a "fresh" fetch can be served from a stale entry.
 *
 * Both tokens below are owned by scripts/deploy.sh. Leave them alone — a
 * hand-edited version string is the failure mode this template exists to
 * remove, and a hand-maintained precache list drifts from the module graph.
 */

const CACHE_VERSION = '{{BUILD_ID}}';
const CACHE_NAME = `sounds-${CACHE_VERSION}`;

/* The audio lives in its own cache, versioned on the assets tree ALONE. Two
 * reasons, and both bite hard if you merge it back into the shell cache:
 *
 *   1. cache.addAll is ATOMIC. 4.4 MB of MP3 in SHELL_ASSETS means one dropped
 *      request on hotel wifi fails the whole install and the app gets no
 *      offline support at all.
 *   2. CACHE_NAME hashes the entire tree, so a one-line CSS change would make
 *      every installed phone re-download all the audio.
 *
 * Both lists and both hashes are generated by scripts/deploy.sh. */
const MEDIA_VERSION = '{{MEDIA_ID}}';
const MEDIA_CACHE = `sounds-media-${MEDIA_VERSION}`;

const SHELL_ASSETS = [/*{{PRECACHE_LIST}}*/];
const MEDIA_ASSETS = [/*{{MEDIA_LIST}}*/];

const MEDIA_RE = /\.(png|jpe?g|webp|gif|svg|ico|woff2?|ttf|mp3|ogg|wav)$/i;

/* Warming the media cache is an OPTIMISATION, not a correctness requirement:
 * .mp3 already routes to cacheFirst, which caches on a miss, so anything this
 * fails to fetch is simply backfilled the first time it is played. That is why
 * it may never reject — it runs inside install's waitUntil purely to keep the
 * worker alive long enough to finish. */
async function warmMedia() {
  if (self.navigator?.connection?.saveData) return;
  let cache;
  try { cache = await caches.open(MEDIA_CACHE); } catch { return; }

  // Serial on purpose: eight parallel MP3 downloads on a weak connection is how
  // you get eight timeouts instead of three files.
  for (const url of MEDIA_ASSETS) {
    try {
      if (await cache.match(url)) continue;
      // fetch+put, never cache.add: add() uses a plain fetch that reads the
      // browser's HTTP cache, which is exactly the staleness the ingress's
      // `expires off;` note exists to prevent.
      const resp = await fetch(url, { cache: 'no-store' });
      // A 404 HTML page stored under an .mp3 key is silent poison — it decodes
      // as garbage forever after.
      if (resp.ok) await cache.put(url, resp);
    } catch { /* flaky link; cacheFirst backfills on first play */ }
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(SHELL_ASSETS);   // atomic and small — if THIS fails, install should
    await warmMedia();                  // cannot reject
    // No skipWaiting() here. Swapping the controller under a live page can leave
    // it running old JS against new cached assets. src/sw-update.js decides when.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    // MEDIA_CACHE is spared so a code-only deploy does not evict the audio.
    // Old media caches still go, but only when MEDIA_ID actually changes.
    await Promise.all(keys
      .filter((k) => k !== CACHE_NAME && k !== MEDIA_CACHE)
      .map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

async function cacheFirst(request) {
  const hit = await caches.match(request);
  if (hit) return hit;
  try {
    const resp = await fetch(request);
    if (resp.ok) (await caches.open(CACHE_NAME)).put(request, resp.clone());
    return resp;
  } catch {
    return Response.error();
  }
}

async function networkFirst(request) {
  try {
    const resp = await fetch(request, { cache: 'no-store' });
    if (resp.ok) (await caches.open(CACHE_NAME)).put(request, resp.clone());
    return resp;
  } catch {
    // Offline. Prefer the exact resource, then the app shell for navigations.
    // offline.html is the last resort and is nearly unreachable in practice:
    // index.html is precached, and nginx serves it for unknown paths anyway.
    return (await caches.match(request))
        || (request.mode === 'navigate'
              ? (await caches.match('./index.html')) || (await caches.match('./offline.html'))
              : null)
        // respondWith() must never resolve to undefined — that surfaces as the
        // browser's network-error page instead of anything we control.
        || Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;              // POSTs are not ours to cache
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;   // leave cross-origin to the browser

  // Per-app extension point: add branches for /api/ or anything app-specific
  // HERE, above the media check. Don't edit the two strategy functions.

  if (MEDIA_RE.test(url.pathname)) { event.respondWith(cacheFirst(request)); return; }
  event.respondWith(networkFirst(request));
});
