/* The sound catalog: what rows exist, in what order, with what labels.
 *
 * Presentation data lives here; per-file facts (loop points, default volume,
 * credit) come from assets/audio/manifest.json, which is generated by
 * scripts/synth-audio.py and scripts/prep-rain.py. Loop points are deliberately
 * NOT duplicated here — CLAUDE.md requires the engine to read them from the
 * manifest, and a second copy is how they drift.
 */

export const AUDIO_BASE = './assets/audio/';

/* Theta is generated live and must never become a file: joint-stereo MP3 coding
 * folds the channels together and smears the exact per-ear separation a binaural
 * beat depends on. Generated rows also never count as "missing".
 *
 * The beat is 6 Hz in every variant — the middle of the 4-8 Hz theta band. What
 * differs is the CARRIER, which is free to choose because the beat is the
 * *difference* between the two tones, not their pitch.
 *
 * Carrier matters enormously on a phone speaker, which cannot move air low down.
 * Measured, at matched loudness, against the rain beds:
 *
 *     binaural 200/206   -63.6 LUFS through a phone speaker   (rain: ~-26)
 *     binaural 400/406   -40.0
 *     binaural 528/534   -31.7
 *     binaural 700/706   -27.0   -- parity with rain
 *     isochronic 528     -31.8
 *
 * The trade runs the other way for the effect itself: the binaural percept is
 * strongest at low carriers and degrades above roughly 1 kHz. So there is no
 * single right answer and these are all offered as rows to pick between.
 *
 * `gain` is a per-variant source trim. A raw oscillator peaks at 1.0, about
 * 25 dB hotter than the mastered files; these values put each variant at
 * -26 LUFS, the same figure every MP3 is mastered to. They are measured, not
 * guessed, and they differ slightly because K-weighting is frequency-dependent.
 * Matching them is what makes the comparison a comparison of timbre and not of
 * loudness. */
export const THETA_BEAT = 6;

export const GROUPS = [
  { id: 'rain', title: 'Rain' },
  { id: 'thunder', title: 'Thunder' },
  { id: 'theta', title: 'Theta' },
];

/* Ordered. rain-true leads because it is the real recording and heads the
 * bedtime mix; the synthesised surfaces follow, roughest-to-brightest. */
const ENTRIES = [
  { id: 'rain-true', group: 'rain', icon: 'ic-rain',
    label: 'Rain (real recording)', caption: 'field recording' },
  { id: 'rain-field', group: 'rain', icon: 'ic-rain', label: 'Rain (open air)' },
  { id: 'rain-window', group: 'rain', icon: 'ic-window', label: 'Rain on window / tent' },
  { id: 'rain-shingle-roof', group: 'rain', icon: 'ic-roof', label: 'Rain on shingle roof' },
  { id: 'rain-metal-roof', group: 'rain', icon: 'ic-roof', label: 'Rain on metal roof' },
  { id: 'rain-tin-roof', group: 'rain', icon: 'ic-roof', label: 'Rain on tin roof' },

  { id: 'thunder-distant', group: 'thunder', icon: 'ic-thunder', label: 'Distant rumble' },
  { id: 'thunder-close', group: 'thunder', icon: 'ic-thunder', label: 'Close thunder' },

  // All 6 Hz. Pick by ear — the captions state the trade honestly.
  { id: 'theta-200', group: 'theta', icon: 'ic-wave', kind: 'generator',
    mode: 'binaural', carrier: 200, gain: 0.0562,
    label: 'Theta 200 Hz', caption: 'deepest — headphones only, a phone speaker cannot reproduce it' },
  { id: 'theta-400', group: 'theta', icon: 'ic-wave', kind: 'generator',
    mode: 'binaural', carrier: 400, gain: 0.0545,
    label: 'Theta 400 Hz', caption: 'strongest beat; still faint without headphones' },
  { id: 'theta-528', group: 'theta', icon: 'ic-wave', kind: 'generator',
    mode: 'binaural', carrier: 528, gain: 0.0539,
    label: 'Theta 528 Hz', caption: 'balanced — audible on a speaker, beat still solid' },
  { id: 'theta-700', group: 'theta', icon: 'ic-wave', kind: 'generator',
    mode: 'binaural', carrier: 700, gain: 0.0533,
    label: 'Theta 700 Hz', caption: 'as loud as the rain rows; beat weaker at this pitch' },
  { id: 'theta-iso-528', group: 'theta', icon: 'ic-wave', kind: 'generator',
    mode: 'isochronic', carrier: 528, gain: 0.0884,
    label: 'Isochronic 528 Hz', caption: 'one pulsed tone — the only one that works without headphones' },
];

const DEFAULT_VOLUME = 60;     // spec §1, for anything the manifest does not set

/* Returns { sounds, groups, credits, manifestOk }. Never throws: a catalog that
 * fails to load must still render rows, and theta must still play. */
export async function loadCatalog() {
  let manifest = {};
  let manifestOk = true;
  try {
    const resp = await fetch(`${AUDIO_BASE}manifest.json`);
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    manifest = await resp.json();
  } catch (err) {
    console.warn('[catalog] audio manifest unavailable', err);
    manifestOk = false;
  }

  const sounds = new Map();
  for (const entry of ENTRIES) {
    const kind = entry.kind ?? 'file';

    if (kind === 'generator') {
      sounds.set(entry.id, {
        ...entry, kind,
        beat: THETA_BEAT,
        // Binaural needs the pair spelled out; isochronic uses carrier + beat.
        left: entry.carrier,
        right: entry.carrier + THETA_BEAT,
        defaultVolume: DEFAULT_VOLUME,
        missing: false,
      });
      continue;
    }

    const m = manifest[entry.id];
    if (!m?.file) {
      sounds.set(entry.id, {
        ...entry, kind,
        defaultVolume: DEFAULT_VOLUME,
        missing: true,
        missingReason: 'audio file missing',
      });
      continue;
    }

    sounds.set(entry.id, {
      ...entry, kind,
      url: AUDIO_BASE + m.file,
      loopStart: m.loopStart,
      loopEnd: m.loopEnd,
      duration: m.duration,
      defaultVolume: Number.isFinite(m.defaultVolume) ? m.defaultVolume : DEFAULT_VOLUME,
      credit: m.credit,
      license: m.license,
      sourceUrl: m.sourceUrl,
      missing: false,
    });
  }

  /* CC BY requires attribution to travel with the work. deploy.sh strips *.md,
   * so this is rendered in the UI rather than kept in a CREDITS file that would
   * silently never ship. */
  const credits = [...sounds.values()]
    .filter((s) => s.credit)
    .map((s) => ({ label: s.label, credit: s.credit, license: s.license, sourceUrl: s.sourceUrl }));

  return { sounds, groups: GROUPS, credits, manifestOk };
}
